### PR TITLE
Replacement of the logo

### PR DESCRIPTION
**Pull request by OZARIN**
Replaced logos with simple, flat icons.

### CODE REVIEW

**Comment by keraf** [comment]
Thanks for the PR. Unfortunately I would ask some revisions as the new icon uses the Bitcoin logo and I would like to avoid the association with any specific coins. I updated the issue #1 to reflect this, sorry I haven't added that earlier!

**Comment by OZARIN** [comment]
Would something like this work instead?

logo_disabled
logo

Pickaxe icon by Guvnor Co from the Noun Project

**Comment by OZARIN** [comment]
Additionally, I can make a more detailed version for promotion if required.

**Comment by keraf** [comment]
I like the idea! I would maybe suggest a less detailed pickaxe to make the icon recognizable in a lower resolution. What do you think?

**Comment by OZARIN** [comment]
I'll get on that!

**Comment by suhail-sullad** [comment]
How about this one. 
when NoCoin is inactive
nocoin- coinshield inactive

when NoCoin is active
nocoin- coinshield active

**Comment by OZARIN** [comment]
Hi Suhail - I think this icon is too complicated. It needs to be recognisable at much smaller sizes (32x32px). 

What do the hexagons represent? Why is the shield a castle?

Probably just the center section, tidied, would be a better choice for an app icon.

**Comment by suhail-sullad** [comment]
Thanks for the input OZARIN.

The hexagon represent different crypto currencies. Thought of adding individual logos of crypto currency, then again it would make the logo complicated.
The castle shield represent a user's computer( castle in the virtual world ).

**Comment by keraf** [comment]
Thanks for the PR @OZARIN, I'll merge it now and adapt the logo to the different states as described in #3 sometime later today or tomorrow.

@suhail-sullad as @OZARIN mentioned, the logo is too detailed and wouldn't look good at smaller resolutions (in fact I did the same comment for @OZARIN a little higher). I think for now I will go with the pickaxe coin idea as I like the idea and will accept improvement along those lines.

**Pull request merged**
