### PR TITLE
Fixed error when Regex matching

### PR DESCRIPTION
**Pull request by arthurgeron**
The regex match function will return the whole match, you will need to iterate over it with `.exec()`  in order to get multiple matched groups. The javascript will throw an exception if you try to get [1] as urls will only match once.
Working demo: http://jsfiddle.net/kus3ow4e/

Source: https://stackoverflow.com/questions/19913667/javascript-regex-global-match-groups

# Changes
-Removed `jQuery`, it's too heavy and not necessary, replaced with vanilla `JS`
-Added style, animation and fonts to header and buttons
-Replaced multiple buttons with a single and stylish dropdown
-Header is now a link for your repository
-Fixed regex match operation so it will work properly

### CODE REVIEW

**Comment by keraf** [comment]
Thanks for your work @arthurgeron, really appreciated. I will grab this tonight and have a look and merge it if everything is alright.

**Comment by arthurgeron** [comment]
Changed buttons Spacing, shadow size, as well as the extension size itself.
Removed JSECoin from blacklist.
peek

**Comment by keraf** [comment]
On second thoughts, I do not really like the style of too rounded buttons. I would rather see something similar to Github's buttons (slightly rounded and a bit more padding). Regarding the whitelist button, I would suggest making it a dropdown button kind of like Bootstrap's one.

Regarding the other changes, could you split them up in different PRs? It makes it hard to track and merge, and there is some overlapping work on my side with your changes. I have by the same occasion added a wiki page regarding contribution guidelines:  https://github.com/keraf/NoCoin/wiki/Contributions

I will also be in touch with you shortly regarding the Opera Store extension ownership.

**Comment by arthurgeron** [comment]
Hey, I've made the changes you requested. 
I really don't have much free time now, I'm being overwhelmed by work and college assignments and I'm about to get my Bachelor degree. 
Separating functionalities into separate branches and doing separate PRs would take a lot of effort and time, time I do not have now, so I hope you're able to verify and test the changes and take your own conclusions. Have a great day/night 💃

**Comment by keraf** [comment]
Thanks for the changes. Unfortunately I'm quite busy too and it would take me some time mergining the changes in. I would suggest you to maybe re-fork the repo to have a clean base, while still keeping your changes on the side, and submit PRs for the changes you want to get in (for example the design changes). Good luck with your work and studies!

**Pull request closed without merging**
